version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "28017:27017"
    networks:
      - web
    container_name: short_urls_mongo
    restart: always
  redis:
    image: redis
    ports:
      - "6479:6379"
    networks:
      - web
    container_name: short_urls_redis
    restart: always
networks:
  web:
    external: true
